/**
 * orez: pglite-powered zero-sync development backend.
 *
 * starts a pglite instance, tcp proxy, and zero-cache process.
 * replaces docker-based postgresql and zero-cache with a single
 * `bun run` command.
 */

import { spawn, type ChildProcess } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { getConfig, getConnectionString } from './config.js'
import { log } from './log.js'
import { startPgProxy } from './pg-proxy.js'
import { createPGliteInstance, runMigrations } from './pglite-manager.js'
import { findPort } from './port.js'
import { installChangeTracking } from './replication/change-tracker.js'

import type { ZeroLiteConfig } from './config.js'
import type { PGlite } from '@electric-sql/pglite'

export { getConfig, getConnectionString } from './config.js'
export type { LogLevel, ZeroLiteConfig } from './config.js'

export async function startZeroLite(overrides: Partial<ZeroLiteConfig> = {}) {
  const config = getConfig(overrides)

  // find available ports
  const pgPort = await findPort(config.pgPort)
  const zeroPort = config.skipZeroCache
    ? config.zeroPort
    : await findPort(config.zeroPort)
  if (pgPort !== config.pgPort) log.orez(`port ${config.pgPort} in use, using ${pgPort}`)
  if (!config.skipZeroCache && zeroPort !== config.zeroPort)
    log.orez(`port ${config.zeroPort} in use, using ${zeroPort}`)
  config.pgPort = pgPort
  config.zeroPort = zeroPort

  log.orez('starting...')
  log.orez(`data dir: ${resolve(config.dataDir)}`)

  mkdirSync(config.dataDir, { recursive: true })

  // start pglite
  const db = await createPGliteInstance(config)

  // run migrations
  await runMigrations(db, config)

  // install change tracking
  log.orez('installing change tracking')
  await installChangeTracking(db)

  // start tcp proxy
  const pgServer = await startPgProxy(db, config)

  // seed data if needed
  await seedIfNeeded(db, config)

  // write .env.local so `bun dev` connects to orez ports
  writeEnvLocal(config)

  // clean up stale sqlite locks from previous runs
  cleanupStaleLocks(config)

  // start zero-cache
  let zeroCacheProcess: ChildProcess | null = null
  if (!config.skipZeroCache) {
    log.orez('starting zero-cache...')
    zeroCacheProcess = await startZeroCache(config)
    await waitForZeroCache(config)
  } else {
    log.orez('skipping zero-cache (skipZeroCache=true)')
  }

  const stop = async () => {
    log.orez('shutting down...')
    if (zeroCacheProcess && !zeroCacheProcess.killed) {
      zeroCacheProcess.kill('SIGTERM')
      // wait up to 3s for graceful exit, then force kill
      await new Promise<void>((r) => {
        const timeout = setTimeout(() => {
          if (zeroCacheProcess && !zeroCacheProcess.killed) {
            zeroCacheProcess.kill('SIGKILL')
          }
          r()
        }, 3000)
        zeroCacheProcess!.on('exit', () => {
          clearTimeout(timeout)
          r()
        })
      })
    }
    pgServer.close()
    await db.close()
    cleanupEnvLocal()
    log.orez('stopped')
  }

  return { config, stop }
}

const ENV_LOCAL_PATH = resolve('.env.local')
const ENV_LOCAL_MARKER = '# auto-generated by orez'

function writeEnvLocal(config: ZeroLiteConfig): void {
  const upstreamUrl = getConnectionString(config, 'postgres')
  const cvrUrl = getConnectionString(config, 'zero_cvr')
  const cdbUrl = getConnectionString(config, 'zero_cdb')

  const content = `${ENV_LOCAL_MARKER}
VITE_PORT_POSTGRES=${config.pgPort}
VITE_PORT_ZERO=${config.zeroPort}
VITE_PUBLIC_ZERO_SERVER="http://localhost:${config.zeroPort}"
ZERO_UPSTREAM_DB="${upstreamUrl}"
ZERO_CVR_DB="${cvrUrl}"
ZERO_CHANGE_DB="${cdbUrl}"
`
  writeFileSync(ENV_LOCAL_PATH, content)
  log.orez('wrote .env.local for dev server')
}

function cleanupStaleLocks(config: ZeroLiteConfig): void {
  const replicaPath = resolve(config.dataDir, 'zero-replica.db')
  for (const suffix of ['-wal', '-shm', '-wal2']) {
    const lockFile = replicaPath + suffix
    try {
      if (existsSync(lockFile)) {
        unlinkSync(lockFile)
        log.orez(`cleaned up stale ${suffix} lock`)
      }
    } catch {
      // ignore
    }
  }
}

function cleanupEnvLocal(): void {
  try {
    if (existsSync(ENV_LOCAL_PATH)) {
      const content = readFileSync(ENV_LOCAL_PATH, 'utf-8')
      if (content.startsWith(ENV_LOCAL_MARKER)) {
        unlinkSync(ENV_LOCAL_PATH)
        log.orez('cleaned up .env.local')
      }
    }
  } catch {
    // ignore cleanup errors
  }
}

async function seedIfNeeded(db: PGlite, config: ZeroLiteConfig): Promise<void> {
  // check if we already have data
  try {
    const result = await db.query<{ count: string }>(
      'SELECT count(*) as count FROM public."user"'
    )
    if (Number(result.rows[0].count) > 0) {
      return
    }
  } catch {
    // table might not exist yet
  }

  log.orez('seeding demo data...')
  const seedFile = resolve(config.seedFile)
  if (!existsSync(seedFile)) {
    log.orez('no seed file found, skipping')
    return
  }

  const sql = readFileSync(seedFile, 'utf-8')
  const statements = sql
    .split('--> statement-breakpoint')
    .map((s) => s.trim())
    .filter(Boolean)

  for (const stmt of statements) {
    await db.exec(stmt)
  }
  log.orez('seeded demo data')
}

function patchSqliteForWasm(): void {
  // replace @rocicorp/zero-sqlite3 with bedrock-sqlite (wasm) so
  // zero-cache uses wasm instead of native bindings
  try {
    const sqlitePkgEntry = import.meta
      .resolve('@rocicorp/zero-sqlite3')
      .replace('file://', '')
    const libDir = resolve(sqlitePkgEntry, '..')
    const indexPath = resolve(libDir, 'index.js')
    if (!existsSync(indexPath)) return

    const current = readFileSync(indexPath, 'utf-8')
    if (current.includes('bedrock-sqlite')) return // already patched

    // resolve bedrock-sqlite's dist entry point
    const bedrockEntry = import.meta.resolve('bedrock-sqlite').replace('file://', '')
    if (!existsSync(bedrockEntry)) {
      log.orez('bedrock-sqlite not found, skipping wasm patch')
      return
    }

    // inline the full shim into index.js - no external file dependency
    const shim = `'use strict';
// patched by orez: bedrock-sqlite (wasm) replaces native bindings
var mod = require('${bedrockEntry}');
var Database = mod.Database;
var SqliteError = mod.SqliteError;

// patch methods zero-cache needs but bedrock-sqlite doesn't have
// set busy_timeout on every db open - wasm vfs can't share locks between processes,
// so retrying on SQLITE_BUSY prevents "database is locked" errors
Database.prototype.unsafeMode = function() {
  try {
    this.pragma('busy_timeout = 5000');
    this.pragma('journal_mode = wal');
    this.pragma('synchronous = normal');
  } catch(e) {}
  return this;
};
if (!Database.prototype.defaultSafeIntegers) Database.prototype.defaultSafeIntegers = function() { return this; };
if (!Database.prototype.serialize) Database.prototype.serialize = function() { throw new Error('not supported in wasm'); };
if (!Database.prototype.backup) Database.prototype.backup = function() { throw new Error('not supported in wasm'); };

// patch Statement prototype
var tmpDb = new Database(':memory:');
var tmpStmt = tmpDb.prepare('SELECT 1');
var SP = Object.getPrototypeOf(tmpStmt);
if (!SP.safeIntegers) SP.safeIntegers = function() { return this; };
if (!SP.scanStatusV2) SP.scanStatusV2 = function() { return []; };
if (!SP.scanStatusReset) SP.scanStatusReset = function() {};
tmpDb.close();

// scanstat constants
Database.SQLITE_SCANSTAT_NLOOP = 0;
Database.SQLITE_SCANSTAT_NVISIT = 1;
Database.SQLITE_SCANSTAT_EST = 2;
Database.SQLITE_SCANSTAT_NAME = 3;
Database.SQLITE_SCANSTAT_EXPLAIN = 4;
Database.SQLITE_SCANSTAT_SELECTID = 5;
Database.SQLITE_SCANSTAT_PARENTID = 6;
Database.SQLITE_SCANSTAT_NCYCLE = 7;
Database.SQLITE_SCANSTAT_COMPLEX = 8;

module.exports = Database;
module.exports.SqliteError = SqliteError;
`
    writeFileSync(indexPath, shim)

    // also patch database.js since it has top-level native addon loading
    const dbPath = resolve(libDir, 'database.js')
    if (existsSync(dbPath)) {
      writeFileSync(dbPath, `'use strict';\nmodule.exports = require('./index');\n`)
    }

    log.orez('patched @rocicorp/zero-sqlite3 -> bedrock-sqlite (wasm)')
  } catch (e) {
    log.orez(`sqlite wasm patch failed: ${e}`)
  }
}

async function startZeroCache(config: ZeroLiteConfig): Promise<ChildProcess> {
  // resolve @rocicorp/zero entry, cli.js is right next to it
  let zeroCacheBin = ''
  try {
    const entry = import.meta.resolve('@rocicorp/zero').replace('file://', '')
    const bin = resolve(entry, '..', 'cli.js')
    if (existsSync(bin)) zeroCacheBin = bin
  } catch {
    // package not resolvable
  }

  if (!zeroCacheBin) {
    throw new Error('zero-cache binary not found. install @rocicorp/zero')
  }

  // patch sqlite to use wasm before spawning zero-cache
  patchSqliteForWasm()

  const upstreamUrl = getConnectionString(config, 'postgres')
  const cvrUrl = getConnectionString(config, 'zero_cvr')
  const cdbUrl = getConnectionString(config, 'zero_cdb')

  // defaults that can be overridden by user env
  const defaults: Record<string, string> = {
    NODE_ENV: 'development',
    ZERO_LOG_LEVEL: config.logLevel,
    ZERO_NUM_SYNC_WORKERS: '1',
  }

  const env: Record<string, string> = {
    ...defaults,
    ...(process.env as Record<string, string>),
    // these must be set by orez
    ZERO_UPSTREAM_DB: upstreamUrl,
    ZERO_CVR_DB: cvrUrl,
    ZERO_CHANGE_DB: cdbUrl,
    ZERO_REPLICA_FILE: resolve(config.dataDir, 'zero-replica.db'),
    ZERO_PORT: String(config.zeroPort),
  }

  const child = spawn(zeroCacheBin, [], {
    env,
    stdio: ['ignore', 'pipe', 'pipe'],
  })

  child.stdout?.on('data', (data: Buffer) => {
    const lines = data.toString().trim().split('\n')
    for (const line of lines) {
      log.zero(line)
    }
  })

  child.stderr?.on('data', (data: Buffer) => {
    const lines = data.toString().trim().split('\n')
    for (const line of lines) {
      log.zero(line)
    }
  })

  child.on('exit', (code) => {
    if (code !== 0 && code !== null) {
      log.zero(`exited with code ${code}`)
    }
  })

  return child
}

async function waitForZeroCache(
  config: ZeroLiteConfig,
  timeoutMs = 60000
): Promise<void> {
  const start = Date.now()
  const url = `http://127.0.0.1:${config.zeroPort}/`

  while (Date.now() - start < timeoutMs) {
    try {
      const res = await fetch(url)
      if (res.ok) {
        log.zero('ready')
        return
      }
    } catch {
      // not ready yet
    }
    await new Promise((r) => setTimeout(r, 500))
  }

  log.zero('health check timed out, continuing anyway')
}
